cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
            "//external:gflags",
            "//external:glog",
            "//ptr:ptr",
            "//sort:sort",
            ],
)
